http.host: "0.0.0.0"
http.port: 9600
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: ${ELASTICSEARCH_USERNAME:-siscopom}
  password: ${ELASTICSEARCH_PASSWORD:-siscopom}
